name: fucking_do_it
description: Just Fucking Do It
version: 0.0.1+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  get_it: ^7.2.0
  dafluta: ^5.1.1
  link_text: ^0.2.0
  url_strategy: ^0.2.0
  google_sign_in: ^6.0.2
  cached_network_image: ^3.2.3
  
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter 

dev_dependencies:
  dalocale: ^2.4.2
  daassets: ^1.3.2
  daunused: ^1.3.0
  dapublock: ^1.0.1
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/FontsFree-Net-proxima_nova_reg-webfont.ttf

  assets:
    - assets/images/